# Generated by Django 5.1.1 on 2024-09-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('Loanid', models.IntegerField(primary_key=True, serialize=False)),
                ('Customername', models.CharField(max_length=50)),
                ('Salary_slips', models.IntegerField()),
                ('Accountno', models.IntegerField()),
                ('Adharno', models.IntegerField()),
            ],
        ),
    ]
